# Generated by Django 4.0.4 on 2022-05-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_candidato_id_alter_recrutador_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserClient',
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='descricao',
            field=models.TextField(),
        ),
    ]
